name: Tests and Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        step:
          - tests
          - lint

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt && python setup.py develop
          STEP="${{ matrix.step}}" ./.ci-before-script.sh
      - name: Run tests or lint
        run: |
          STEP="${{ matrix.step}}" ./.ci-runs-tests.sh
